@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.example.GameTimer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Engine1526836320[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Engine</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   database: Database [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   game: GameDescription [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   parser: Parser [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timer: GameTimer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ loadSavedGame()</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ newGame()</TD></TR>
<TR><TD ALIGN="LEFT" >+ playGame(game: GameDescription)</TD></TR>
<TR><TD ALIGN="LEFT" >- printGameIntro(playerName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- saveGame(game: GameDescription)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GameTimer1526836320[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GameTimer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   running: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   secondsElapsed: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ resetTimer()</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumeTimer()</TD></TR>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
<TR><TD ALIGN="LEFT" >+ stopTimer()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1944009033 { 
   	label=gui
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   MenuSwing1873475245[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MenuSwing</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   engine: Engine [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   execute: CommandsExecution [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   loadGameButton: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   newGameButton: JButton [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ startMenu()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Engine1526836320 -> GameTimer1526836320[label="timer
[0..1]"];
MenuSwing1873475245 -> Engine1526836320[label="engine
[0..1]"];
    
}
@enduml